### ISSUE TITLE
Add support for --avoidRedirects in newman runner

### ISSUE THREAD

**Issue by scottjungers** [michaelruocco/gradle-postman-runner#15]
The newman collection runner has support for avoiding redirects (-R, --avoidRedirects) during a test.  Can you add a parameter to the postman task to allow gradle projects to enable/disable this setting?

**Comment by michaelruocco** [comment]
Apologies for not coming back on this sooner, I don't think I got any email alerts about the issues raised on this repo.

I have just needed to apply a bunch of updates on this repo, so I appreciate that this is very late but this will be released in a new version today.

**Comment by scottjungers** [comment]
Wonderful!  Thanks for your help!

**Comment by michaelruocco** [comment]
Closing as I believe this is now resolved.
