### ISSUE TITLE
gradle-postman-runner not supported for Gradle 6+ version

### ISSUE THREAD

**Issue by SwathiCR** [michaelruocco/gradle-postman-runner#16]
Team we are using this gradle-postman-runner plugin to invoke the newman collections from gradle. We initially started it with 5.4.1 version of gradle. This plugin worked like MAGIC for us. Now we have upgraded the gradle version to 6+. Currently we are facing issue to execute the plugin. We are seeing a Node version mismatch. Can you please guide us how we can use this plugin for gradle 6+

**Comment by michaelruocco** [comment]
Apologies for the delayed response, I don't seem to be getting notifications for these issue requests. Either that or I have just been too busy and missed the messages. What is the issue specific node mismatch error you are seeing? I have a couple of projects using this plugin with gradle 6.8.3 and they all seem to be working fine?

https://github.com/michaelruocco/idv-context/blob/master/gradle/wrapper/gradle-wrapper.properties#L3
https://github.com/michaelruocco/idv-context/blob/master/app/spring/build.gradle#L14

https://github.com/michaelruocco/idv-context/blob/master/gradle/wrapper/gradle-wrapper.properties#L3
https://github.com/michaelruocco/idv-one-time-passcode/blob/master/app/spring/build.gradle#L14

If you can share some more details about the issue you are seeing and maybe push a repo with an example I can see about taking a more detailed look?

**Comment by michaelruocco** [comment]
I am closing this for now, feel free to reopen if you have some more details or an example you can share that recreates the issue.
