### ISSUE TITLE
Utilize Newman command line options 

### ISSUE THREAD

**Issue by SAZware** [michaelruocco/gradle-postman-runner#17]
Is there a way to pass Newman command line options (e.g. --global-var, --env-var) via the gradle-postman-runner task?

**Comment by michaelruocco** [comment]
Apologies for the delayed response, I think either I am not getting email notifications for this repo, either that or I have just been busy and missed them! This is not currently supported, but I may need to look into this shortly for my own purposes, if I find the time and have any joy I will update here to let you know.

**Comment by michaelruocco** [comment]
I have added the ability to set a globals file, as well as global vars and env vars in a change that I have raised and released today.

**Comment by michaelruocco** [comment]
Closing this as I believe it is now resolved, please re open or raise a new issue if you require any further options to be added.
